#%RAML 1.0 Library
uses:
  core: coreLib.raml
types:
  Type:
    properties:
      name:
        type: string
        (core.unique): true
      description?: core.markdown
      type:
        type: string
        enum: [ object,string, number,boolean]
      properties:
        type: Type[]
        (core.visibleWhen): $.type='object'
  Library:
    properties:
      name: string
      types: Type[]