#%RAML 1.0 Library
uses:
  animals: ./animals.raml
  annotations: ./annotations.raml
types:
  HasId:
    properties:
      id: integer
  Items:
    properties:
        name:
          type: string
        commonNames:
          type: string[]
          default: ["Pavel", "Denis", "Max"]
  Named:
      properties:
       name: string
  Person:
    type: [ HasId , Named]
    properties:
      lastName: string
      age: number
      pets?: Named[]
  Company:
    type: HasId
    displayName: Company
    description: Company of Heroes
    (annotations.Elements): ["name"]
    properties:
      name: string
      public?: boolean
      members: Person[]
      ownedBy: Company | Person | string
  Persons: Person[]
  Pet:
    type: animals.Pet
    properties:
      ExtraInfo: string
  Map:
    properties:
      //: string
  OwnedBy: Company | Person | string